TrainingPlanning/Models/DepartmentViewModel.cs
using System.Collections.Generic;
using AMWD.ASBHE.TrainingPlanning.Database.Entities;

namespace AMWD.ASBHE.TrainingPlanning.Models
{
	public class DepartmentViewModel
	{
		public List<Department> Departments { get; set; }

		#region Department Entity

		public int Id { get; set; }

		public string Name { get; set; }

		public string Contact { get; set; }

		public string EmailAddress { get; set; }

		public string PhoneNumber { get; set; }

		public string Street { get; set; }

		public string AddressAddition { get; set; }

		public string ZipCode { get; set; }

		public string City { get; set; }

		public string Country { get; set; }

		public bool IsDeleted { get; set; }

		#endregion Department Entity
	}
}

TrainingPlanning/Controllers/DepartmentsController.cs
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AMWD.ASBHE.TrainingPlanning.Database;
using AMWD.ASBHE.TrainingPlanning.Database.Entities;
using AMWD.ASBHE.TrainingPlanning.Extensions;
using AMWD.ASBHE.TrainingPlanning.Models;
using AMWD.ASBHE.TrainingPlanning.Security;
using AMWD.ASBHE.TrainingPlanning.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace AMWD.ASBHE.TrainingPlanning.Controllers
{
	[Authorize]
	public class DepartmentsController : Controller
	{
		private readonly ILogger _logger;
		private readonly ServerDbContext _dbContext;
		private readonly ExtendedFakeFilterService _fakeFilterService;

		public DepartmentsController(ILogger<DepartmentsController> logger, ServerDbContext dbContext, ExtendedFakeFilterService fakeFilterService)
		{
			_logger = logger;
			_dbContext = dbContext;
			_fakeFilterService = fakeFilterService;
		}

		public async Task<IActionResult> Index(CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			var model = new DepartmentViewModel
			{
				Departments = await _dbContext.Departments
					.OrderBy(d => d.IsDeleted)
					.ThenBy(d => d.Name)
					.ToListAsync(cancellationToken)
			};

			ViewData["Title"] = "Bereiche";
			return View(model);
		}

		public IActionResult Create()
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			ViewData["Title"] = "Neuer Bereich";
			return View(nameof(Edit), new DepartmentViewModel());
		}

		public async Task<IActionResult> Edit(int id, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			var department = await _dbContext.Departments
				.Where(d => d.Id == id)
				.FirstOrDefaultAsync(cancellationToken);
			if (department == null)
				return NotFound();

			var model = new DepartmentViewModel
			{
				Id = department.Id,
				AddressAddition = department.AddressAddition,
				Contact = department.Contact,
				City = department.City,
				Country = department.Country,
				EmailAddress = department.EmailAddress,
				IsDeleted = department.IsDeleted,
				Name = department.Name,
				PhoneNumber = department.PhoneNumber,
				Street = department.Street,
				ZipCode = department.ZipCode
			};

			ViewData["Title"] = "Bereich bearbeiten";
			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(DepartmentViewModel model, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			ViewData["Title"] = model.Id > 0 ? "Bereich bearbeiten" : "Neuer Bereich";

			if (string.IsNullOrWhiteSpace(model.Name))
				ModelState.AddModelError(nameof(model.Name), "Ein Name ist erforderlich");
			else
			{
				model.Name = model.Name.Trim();
				if (await _dbContext.Departments.Where(d => !d.IsDeleted).Where(d => d.Id != model.Id).Where(d => d.Name.ToLower() == model.Name.ToLower()).AnyAsync(cancellationToken))
					ModelState.AddModelError(nameof(model.Name), "Der Name ist bereits vorhanden");
			}

			if (!string.IsNullOrWhiteSpace(model.EmailAddress))
			{
				model.EmailAddress = model.EmailAddress.Trim().ToLower();

				if (!model.EmailAddress.IsValidEmailAddress())
					ModelState.AddModelError(nameof(model.EmailAddress), "Die E-Mail Adresse ist nicht gültig");
				else if (!await _fakeFilterService.IsEmailValid(model.EmailAddress, cancellationToken))
					ModelState.AddModelError(nameof(model.EmailAddress), "Der E-Mail Anbieter wird als unsicher eingestuft");
			}

			if (!ModelState.IsValid)
				return View(model);

			var department = await _dbContext.Departments
				.Where(d => d.Id == model.Id)
				.FirstOrDefaultAsync(cancellationToken);
			if (department == null)
			{
				department = new Department();
				await _dbContext.Departments.AddAsync(department, cancellationToken);
			}

			department.Name = model.Name;
			department.Contact = model.Contact?.Trim();
			department.PhoneNumber = model.PhoneNumber?.Trim();
			department.EmailAddress = model.EmailAddress;
			department.Street = model.Street?.Trim();
			department.AddressAddition = model.AddressAddition?.Trim();
			department.ZipCode = model.ZipCode?.Trim();
			department.City = model.City?.Trim();
			department.Country = model.Country?.Trim();
			department.IsDeleted = model.IsDeleted;

			try
			{
				await _dbContext.SaveChangesAsync(cancellationToken);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, $"Saving department failed: {ex.GetMessage()}");
				return StatusCode(StatusCodes.Status500InternalServerError);
			}
		}

		// This method is a REST style endpoint to provide additional functionality
		[HttpPost]
		public async Task<IActionResult> HardDelete(int id, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid("Admin permission required");

			var department = await _dbContext.Departments
				.Where(d => d.IsDeleted)
				.Where(d => d.Id == id)
				.FirstOrDefaultAsync(cancellationToken);
			if (department == null)
				return NotFound("No department with this id available to hard delete");

			int userCount = await _dbContext.Users
				.Where(u => u.DepartmentId == department.Id)
				.CountAsync(cancellationToken);
			if (userCount > 0)
				return BadRequest("Some users are still mapped to this department");

			int participantCount = await _dbContext.Participants
				.Where(p => p.DepartmentId == department.Id)
				.CountAsync(cancellationToken);
			if (participantCount > 0)
				return BadRequest("Some participants are still mapped to this department");

			try
			{
				_dbContext.Departments.Remove(department);
				await _dbContext.SaveChangesAsync(cancellationToken);

				_logger.LogWarning($"User #{authUser.Id} ({authUser.EmailAddress}) dropped department '{department.Name}'");
				return Ok();
			}
			catch (Exception ex)
			{
				return StatusCode(StatusCodes.Status500InternalServerError, ex.GetRecursiveMessage());
			}
		}
	}
}

TrainingPlanning/Views/Departments/Edit.cshtml
@model DepartmentViewModel

<h1 class="h1"><span class="fa-solid fa-fw fa-building-user"></span> Bereich</h1>

<form asp-area="" asp-controller="Departments" asp-action="Edit" asp-route-id="" method="post">
	<input asp-for="Id" type="hidden" value="@Model.Id" />

	<div class="row g-3 mb-3">
		<div class="col-sm">
			<label asp-for="Name" class="form-label">Name</label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name"></span>
		</div>
		<div class="col-sm">
			<label asp-for="Contact" class="form-label">Ansprechpartner</label>
			<input asp-for="Contact" class="form-control" />
			<span asp-validation-for="Contact"></span>
		</div>
	</div>

	<div class="row g-3 mb-3">
		<div class="col-sm">
			<label asp-for="EmailAddress" class="form-label">E-Mail Adresse</label>
			<input asp-for="EmailAddress" class="form-control" type="email" />
			<span asp-validation-for="EmailAddress"></span>
		</div>
		<div class="col-sm">
			<label asp-for="PhoneNumber" class="form-label">Telefon</label>
			<input asp-for="PhoneNumber" class="form-control" type="tel" />
		</div>
	</div>

	<div class="row g-3 mb-3">
		<div class="col-sm">
			<label class="form-label">Adresse</label>
			<div class="input-group">
				<input asp-for="Street" class="form-control" placeholder="Straße + Haus Nr." />
			</div>
		</div>
		<div class="col-sm">
			<label class="form-label d-none d-sm-block">&nbsp;</label>
			<div class="input-group">
				<input asp-for="ZipCode" class="form-control" placeholder="PLZ" />
				<input asp-for="City" class="form-control" placeholder="Stadt" />
			</div>
		</div>
	</div>

	<div class="row g-3 mb-3">
		<div class="col-sm">
			<label asp-for="AddressAddition" class="form-label">Adress-Zusatz</label>
			<input asp-for="AddressAddition" class="form-control" />
		</div>
		<div class="col-sm">
			<label asp-for="Country" class="form-label">Land</label>
			<input asp-for="Country" class="form-control" />
		</div>
	</div>

	<div class="row g-3 mb-3">
		<div class="col-sm">
			<div class="form-check form-switch">
				<input asp-for="IsDeleted" class="form-check-input" type="checkbox" />
				<label asp-for="IsDeleted" class="form-check-label">gelöscht</label>
			</div>
		</div>
	</div>

	<div class="row g-3 mb-3">
		<div class="col-sm">
			<button type="submit" class="btn btn-outline-primary">Speichern</button>
			<a asp-area="" asp-controller="Departments" asp-action="Index" asp-route-id="" class="btn btn-outline-secondary">Abbrechen</a>
		</div>
	</div>
</form>

TrainingPlanning/Views/Departments/Index.cshtml
@model DepartmentViewModel

<h1 class="h1"><span class="fa-solid fa-fw fa-building-user"></span> Bereiche</h1>

<div class="table-responsive">
	<table class="table">
		<thead class="table-light">
			<tr>
				<th scope="col">Name</th>
				<th scope="col">Ansprechpartner</th>
				<th scope="col">Erreichbarkeit (E-Mail/Telefon)</th>
				<th scope="col" class="text-end">
					<a asp-area="" asp-controller="Departments" asp-action="Create" asp-route-id="" class="btn btn-sm btn-success" title="Neuer Bereich">
						<span class="fa-solid fa-fw fa-plus"></span>
					</a>
				</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var department in Model.Departments)
			{
				<tr condition-class-text-decoration-line-through="@(department.IsDeleted)">
					<td>@department.Name</td>
					<td>@department.Contact</td>
					<td>
						@department.EmailAddress / @department.PhoneNumber
					</td>
					<td class="text-end">
						<a asp-area="" asp-controller="Departments" asp-action="Edit" asp-route-id="@department.Id" class="btn btn-sm btn-outline-primary" title="bearbeiten">
							<span class="fa-solid fa-fw fa-pen"></span>
						</a>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>