TrainingPlanning/Controllers/MetaController.cs
using System.Text;
using AMWD.ASBHE.TrainingPlanning.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json.Linq;

namespace AMWD.ASBHE.TrainingPlanning.Controllers
{
	public class MetaController : Controller
	{
		private readonly IConfiguration _configuration;

		public MetaController(IConfiguration configuration)
		{
			_configuration = configuration;
		}

		public IActionResult Manifest()
		{
			string host = _configuration.GetValue("ASPNETCORE_APPL_URL", HttpContext.Request.Scheme + "://" + HttpContext.Request.Host);
			string path = _configuration.GetValue("ASPNETCORE_APPL_PATH", HttpContext.Request.PathBase.ToString());

			var manifest = new JObject
			{
				["name"] = "Katastrophenschut ASB Hessen",
				["short_name"] = "ASB HE KatS",
				["description"] = "Seminarprogramm und Anmeldung für den Katastrophenschutz des ASB Landesverband Hessen",
				["icons"] = new JArray
				{
					new JObject
					{
						["src"] = $"{path}/ico/android-chrome-192x192.png",
						["sizes"] = "192x192",
						["type"] = "image/png"
					},
					new JObject
					{
						["src"] = $"{path}/ico/android-chrome-512x512.png",
						["sizes"] = "512x512",
						["type"] = "image/png"
					}
				},
				["theme_color"] = "#fff",
				["background_color"] = "#ccc",
				["display"] = "standalone",
				["scope"] = $"{path}/",
				["start_url"] = $"{host}{path}"
			};

			Response.ContentType = "application/manifest+json";
			return Json(manifest);
		}

		public IActionResult BrowserConfig()
		{
			string path = _configuration.GetValue("ASPNETCORE_APPL_PATH", HttpContext.Request.PathBase.ToString());

			var sb = new StringBuilder();
			sb.AppendLine($"<?xml version=\"1.0\" encoding=\"utf-8\" ?>");
			sb.AppendLine($"<browserconfig>");
			sb.AppendLine($"	<msapplication>");
			sb.AppendLine($"		<tile>");
			sb.AppendLine($"			<square70x70logo src=\"{path}/mstile-70x70.png\" />");
			sb.AppendLine($"			<TileColor>#ccc</TileColor>");
			sb.AppendLine($"		</tile>");
			sb.AppendLine($"	</msapplication>");
			sb.AppendLine($"</browserconfig>");

			return Content(sb.ToString(), "text/xml", Encoding.UTF8);
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult JavaScript()
		{
			string host = _configuration.GetValue("ASPNETCORE_APPL_URL", HttpContext.Request.Scheme + "://" + HttpContext.Request.Host);
			string path = _configuration.GetValue("ASPNETCORE_APPL_PATH", HttpContext.Request.PathBase.ToString());

			var (formName, headerName, tokenValue) = HttpContext.GetAntiforgeryToken();

			var sb = new StringBuilder();

			sb.AppendLine($"TP.Url = '{host}{path}';");
			sb.AppendLine($"TP.Path = '{path}';");
			sb.AppendLine($"TP.Token.FormName = '{formName}';");
			sb.AppendLine($"TP.Token.HeaderName = '{headerName}';");
			sb.AppendLine($"TP.Token.Value = '{tokenValue}';");

			return Content(sb.ToString().Trim(), "text/javascript", Encoding.UTF8);
		}
	}
}

TrainingPlanning/Controllers/ProtocolsController.cs
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AMWD.ASBHE.TrainingPlanning.Database;
using AMWD.ASBHE.TrainingPlanning.Extensions;
using AMWD.ASBHE.TrainingPlanning.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace AMWD.ASBHE.TrainingPlanning.Controllers
{
	[Authorize]
	public class ProtocolsController : Controller
	{
		private readonly IServiceScopeFactory _serviceScopeFactory;

		public ProtocolsController(IServiceScopeFactory serviceScopeFactory)
		{
			_serviceScopeFactory = serviceScopeFactory;
		}

		public IActionResult Index()
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			using var scope = _serviceScopeFactory.CreateScope();
			var logContext = scope.ServiceProvider.GetService<LogDbContext>();

			ViewData["Title"] = "Server-Protokoll";
			ViewData["IsAvailable"] = logContext != null;
			return View();
		}

		public async Task<IActionResult> Get(long id, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			using var scope = _serviceScopeFactory.CreateScope();
			var logContext = scope.ServiceProvider.GetService<LogDbContext>();

			if (logContext == null)
				return Json(Array.Empty<SerilogEntry>());

			try
			{
				var entries = await logContext.Entries
					.Where(e => e.Id < id || id == 0)
					.OrderByDescending(e => e.Id)
					.Take(50)
					.ToListAsync(cancellationToken);

				return Json(entries);
			}
			catch (Exception ex)
			{
				return StatusCode(StatusCodes.Status500InternalServerError, ex.GetMessage());
			}
		}
	}
}

TrainingPlanning/Controllers/SettingsController.cs
using System;
using System.Threading;
using System.Threading.Tasks;
using AMWD.ASBHE.TrainingPlanning.Extensions;
using AMWD.ASBHE.TrainingPlanning.Security;
using AMWD.ASBHE.TrainingPlanning.Services;
using AMWD.ASBHE.TrainingPlanning.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AMWD.ASBHE.TrainingPlanning.Controllers
{
	[Authorize]
	public class SettingsController : Controller
	{
		private readonly GlobalSettingsService _globalSettings;
		private readonly CryptographyHelper _crypto;

		public SettingsController(GlobalSettingsService globalSettings, CryptographyHelper crypto)
		{
			_globalSettings = globalSettings;
			_crypto = crypto;
		}

		public IActionResult Index()
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			ViewData["Title"] = "Einstellungen";
			return View();
		}

		[HttpGet]
		public async Task<IActionResult> Get(string settingName, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			switch (settingName?.ToLower())
			{
				case "smtp":
					var smtpSettings = await _globalSettings.GetAsync<SmtpSettings>(settingName, cancellationToken: cancellationToken);
					return Json(smtpSettings);

				case "terms":
					string terms = await _globalSettings.GetAsync<string>(settingName, cancellationToken: cancellationToken);
					return Json(terms);

				default:
					throw new NotImplementedException();
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Set(string settingName, string settingsJson, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			switch (settingName?.ToLower())
			{
				case "smtp":
					var smtpSettings = settingsJson.DeserializeJson<SmtpSettings>();

					// There is a password, check whether we need to encrypt it
					// (decrypt will fail on plain password)
					if (!string.IsNullOrWhiteSpace(smtpSettings.Password))
					{
						try
						{
							string test = _crypto.DecryptAes(smtpSettings.Password);
						}
						catch
						{
							smtpSettings.Password = _crypto.EncryptAes(smtpSettings.Password);
						}
					}

					await _globalSettings.SetAsync(settingName, smtpSettings, cancellationToken);
					break;

				case "terms":
					string terms = settingsJson.DeserializeJson<string>();
					await _globalSettings.SetAsync(settingName, terms?.Trim(), cancellationToken);
					break;

				default:
					throw new NotImplementedException();
			}

			return Ok();
		}

		[HttpDelete]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete(string settingName, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			await _globalSettings.DeleteAsync(settingName, cancellationToken);
			return Ok();
		}
	}
}

TrainingPlanning/Controllers/UsersController.cs
using System;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using AMWD.ASBHE.TrainingPlanning.Database;
using AMWD.ASBHE.TrainingPlanning.Database.Entities;
using AMWD.ASBHE.TrainingPlanning.Extensions;
using AMWD.ASBHE.TrainingPlanning.Models;
using AMWD.ASBHE.TrainingPlanning.Security;
using AMWD.ASBHE.TrainingPlanning.Services;
using AMWD.ASBHE.TrainingPlanning.Utils;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace AMWD.ASBHE.TrainingPlanning.Controllers
{
	[Authorize]
	public class UsersController : Controller
	{
		private readonly ILogger<UsersController> _logger;
		private readonly ServerDbContext _dbContext;
		private readonly ExtendedFakeFilterService _fakeFilterService;

		public UsersController(ILogger<UsersController> logger, ServerDbContext dbContext, ExtendedFakeFilterService fakeFilterService)
		{
			_logger = logger;
			_dbContext = dbContext;
			_fakeFilterService = fakeFilterService;
		}

		public async Task<IActionResult> Index(CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			var model = new UsersViewModel
			{
				Users = await _dbContext.Users
					.OrderByDescending(u => u.IsEnabled)
					.ThenBy(u => u.EmailAddress)
					.ToListAsync(cancellationToken),
				Departments = await _dbContext.Departments
					.OrderBy(d => d.IsDeleted)
					.ThenBy(d => d.Name)
					.ToListAsync(cancellationToken)
			};

			ViewData["Title"] = "Benutzer";
			return View(model);
		}

		public async Task<IActionResult> Create(CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			var model = new UsersViewModel
			{
				Departments = await _dbContext.Departments
					.OrderBy(d => d.IsDeleted)
					.ThenBy(d => d.Name)
					.ToListAsync(cancellationToken),
				IsEnabled = true
			};

			ViewData["Title"] = "Neuer Benutzer";
			return View(nameof(Edit), model);
		}

		public async Task<IActionResult> Edit(int id, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			var user = await _dbContext.Users
				.Where(u => u.Id == id)
				.FirstOrDefaultAsync(cancellationToken);
			if (user == null)
				return NotFound();

			var model = new UsersViewModel
			{
				Departments = await _dbContext.Departments
					.OrderBy(d => d.IsDeleted)
					.ThenBy(d => d.Name)
					.ToListAsync(cancellationToken),
				Id = user.Id,
				EmailAddress = user.EmailAddress,
				FirstName = user.FirstName,
				LastName = user.LastName,
				IsAdmin = user.IsAdmin,
				IsEnabled = user.IsEnabled,
				DepartmentId = user.DepartmentId
			};

			ViewData["Title"] = "Benutzer bearbeiten";
			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(UsersViewModel model, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			model.Departments = await _dbContext.Departments
					.OrderBy(d => d.IsDeleted)
					.ThenBy(d => d.Name)
					.ToListAsync(cancellationToken);
			ViewData["Title"] = model.Id > 0 ? "Benutzer bearbeiten" : "Neuer Benutzer";

			if (string.IsNullOrWhiteSpace(model.EmailAddress))
			{
				ModelState.AddModelError(nameof(model.EmailAddress), "Eine E-Mail Adresse ist erforderlich");
			}

			model.EmailAddress = model.EmailAddress.Trim().ToLower();

			if (!model.EmailAddress.IsValidEmailAddress())
			{
				ModelState.AddModelError(nameof(model.EmailAddress), "Die E-Mail Adresse ist nicht gültig");
				return View(model);
			}

			if (!await _fakeFilterService.IsEmailValid(model.EmailAddress, cancellationToken))
			{
				ModelState.AddModelError(nameof(model.EmailAddress), "Der E-Mail Anbieter wird als unsicher eingestuft (FakeFilter API)");
				return View(model);
			}

			if (await _dbContext.Users.Where(u => u.Id != model.Id).Where(u => u.EmailAddress == model.EmailAddress).AnyAsync(cancellationToken))
			{
				ModelState.AddModelError(nameof(model.EmailAddress), "Die E-Mail Adresse ist bereits in Verwendung");
				return View(model);
			}

			try
			{
				var user = await _dbContext.Users
					.Where(u => u.Id == model.Id)
					.FirstOrDefaultAsync(cancellationToken);
				if (user == null)
				{
					user = new User
					{
						Id = _dbContext.CreateUserId()
					};
					await _dbContext.Users.AddAsync(user, cancellationToken);
				}

				user.EmailAddress = model.EmailAddress;
				user.FirstName = model.FirstName;
				user.LastName = model.LastName;
				user.IsEnabled = model.IsEnabled;
				user.IsAdmin = model.IsAdmin;
				user.DepartmentId = model.DepartmentId;

				// You're not allowed to downgrade yourself.
				if (user.Id == authUser.Id)
				{
					user.IsEnabled = true;
					user.IsAdmin = true;
				}

				await _dbContext.SaveChangesAsync(cancellationToken);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, $"Saving user (#{model.Id}) failed: {ex.GetMessage()}");
				return StatusCode(StatusCodes.Status500InternalServerError);
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Impersonate(int id, CancellationToken cancellationToken)
		{
			try
			{
				var authUser = HttpContext.GetAuthUser();
				if (!authUser.IsAdmin)
					return Forbid();

				// You're not allowed to impersonate yourself.
				if (authUser.Id == id)
					return BadRequest();

				// Already impersonating
				if (authUser.ImpersonatingId.HasValue)
					return BadRequest();

				var user = await _dbContext.Users
					.Where(u => u.Id == id)
					.FirstOrDefaultAsync(cancellationToken);
				if (user == null)
					return NotFound();

				user.ImpersonatingId = authUser.Id;
				await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, user.GetPrincipal(), new AuthenticationProperties
				{
					AllowRefresh = true,
					IsPersistent = true
				});

				return RedirectToAction("Index", "Trainings");
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, $"Deleting user (#{id}) failed: {ex.GetMessage()}");
				return StatusCode(StatusCodes.Status500InternalServerError);
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete(int id, CancellationToken cancellationToken)
		{
			try
			{
				var authUser = HttpContext.GetAuthUser();
				if (!authUser.IsAdmin)
					return Forbid();

				// You're not allowed to delete yourself.
				if (authUser.Id == id)
					return BadRequest();

				var user = await _dbContext.Users
					.Where(u => u.Id == id)
					.FirstOrDefaultAsync(cancellationToken);
				if (user == null)
					return NotFound();

				_dbContext.Users.Remove(user);
				await _dbContext.SaveChangesAsync(cancellationToken);

				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, $"Deleting user (#{id}) failed: {ex.GetMessage()}");
				return StatusCode(StatusCodes.Status500InternalServerError);
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> GeneratePassword(int id, CancellationToken cancellationToken)
		{
			try
			{
				var authUser = HttpContext.GetAuthUser();
				if (!authUser.IsAdmin)
					return Forbid();

				// You're not allowed to send yourself a new password.
				if (authUser.Id == id)
					return BadRequest();

				using var transaction = await _dbContext.BeginTransactionAsync(cancellationToken);

				var user = await _dbContext.Users
					.Where(u => u.Id == id)
					.FirstOrDefaultAsync(cancellationToken);
				if (user == null)
					return NotFound();

				string password = CryptographyHelper.GetRandomString(14);

				var sb = new StringBuilder();
				sb.AppendLine($"Hallo {user.GetName()},");
				sb.AppendLine();
				sb.AppendLine("Es wurde ein neues Kennwort generiert.");
				sb.AppendLine("Das neue Kennwort ist ab sofort gültig.");
				sb.AppendLine();
				sb.AppendLine($"Es lautet: {password}");
				sb.AppendLine();
				sb.AppendLine("Sollte kein neues Kennwort angefordert worden sein, so wäre eine Meldung beim Administrator sinnvoll.");
				sb.AppendLine();

				var msg = new EmailMessage
				{
					Priority = MimeKit.MessageImportance.High,
					Subject = "Neues Kennwort",
					Message = sb.ToString(),
					IsHtml = false,
				};
				msg.Recipients.Add(new EmailAddress { Name = user.GetName(), Address = user.EmailAddress });
				await _dbContext.EmailMessages.AddAsync(msg, cancellationToken);

				user.PasswordHash = PasswordHelper.HashPassword(password);

				await _dbContext.SaveChangesAsync(cancellationToken);
				await transaction.CommitAsync(cancellationToken);

				return Ok();
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, $"Generating new password for user (#{id}) failed: {ex.GetMessage()}");
				return StatusCode(StatusCodes.Status500InternalServerError, ex.GetMessage());
			}
		}
	}
}

TrainingPlanning/Views/Shared/_Favicon.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="~/ico/apple-touch-icon.png" />
<link rel="icon" type="image/png" sizes="32x32" href="~/ico/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="16x16" href="~/ico/favicon-16x16.png" />
<link rel="manifest" href="@Url.Action("Manifest", "Meta")" />
<link rel="mask-icon" href="~/ico/safari-pinned-tab.svg" color="#c80a14" />
<meta name="msapplication-config" content="@Url.Action("BrowserConfig", "Meta")" />
<meta name="msapplication-TileColor" content="#ffd813" />
<meta name="theme-color" content="#ffd813" />

TrainingPlanning/Views/Shared/_JS.cshtml
@{
	string timeVersion = Program.StartupTime.ToString("yyyyMMddHHmm");
}
<environment include="Development">
	<script type="text/javascript" src="~/lib/luxon/build/global/luxon.js?v=@(timeVersion)" asp-integrity="false"></script>
	<script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.bundle.js?v=@(timeVersion)" asp-integrity="false"></script>
	<script type="text/javascript" src="~/lib/jquery/dist/jquery.js?v=@(timeVersion)" asp-integrity="false"></script>
	<script type="text/javascript" src="~/lib/signalr/dist/browser/signalr.js?v=@(timeVersion)" asp-integrity="false"></script>

	<script type="text/javascript" src="~/js/enums.js?v=@(timeVersion)" asp-integrity="false"></script>
	<script type="text/javascript" src="~/js/models.js?v=@(timeVersion)" asp-integrity="false"></script>

	<script type="text/javascript" src="~/js/global.js?v=@(timeVersion)" asp-integrity="false"></script>
	<script type="text/javascript" src="@Url.Action("JavaScript", "Meta", new { area = "", id = "", v= timeVersion })"></script>
	
	<script type="text/javascript" src="~/js/websocket.js?v=@(timeVersion)" asp-integrity="false"></script>
	<script type="text/javascript" src="~/js/domhelper.js?v=@(timeVersion)" asp-integrity="false"></script>
	<script type="text/javascript" src="~/js/tptoast.js?v=@(timeVersion)" asp-integrity="false"></script>
</environment>
<environment exclude="Development">
	<script type="text/javascript" src="~/lib/luxon/build/global/luxon.min.js?v=@(Program.Version)" asp-integrity="true"></script>
	<script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js?v=@(Program.Version)" asp-integrity="true"></script>
	<script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js?v=@(Program.Version)" asp-integrity="true"></script>
	<script type="text/javascript" src="~/lib/signalr/dist/browser/signalr.min.js?v=@(Program.Version)" asp-integrity="true"></script>

	<script type="text/javascript" src="~/js/enums.js?v=@(Program.Version)" asp-integrity="true"></script>
	<script type="text/javascript" src="~/js/models.js?v=@(Program.Version)" asp-integrity="true"></script>

	<script type="text/javascript" src="~/js/global.js?v=@(Program.Version)" asp-integrity="true"></script>
	<script type="text/javascript" src="@Url.Action("JavaScript", "Meta", new { area = "", id = "", v= Program.Version })"></script>
	
	<script type="text/javascript" src="~/js/websocket.js?v=@(Program.Version)" asp-integrity="true"></script>
	<script type="text/javascript" src="~/js/domhelper.js?v=@(Program.Version)" asp-integrity="true"></script>
	<script type="text/javascript" src="~/js/tptoast.js?v=@(Program.Version)" asp-integrity="true"></script>
</environment>

TrainingPlanning/Views/Shared/_Layout.cshtml
@{
	Func<string, string, string, bool> isActive = (area, controller, action) =>
		string.Equals(ViewContext.RouteData.Values["Area"] as string ?? "", area, StringComparison.OrdinalIgnoreCase) &&
		((string)ViewContext.RouteData.Values["Controller"]).EndsWith(controller, StringComparison.OrdinalIgnoreCase) &&
		(string.Equals(ViewContext.RouteData.Values["Action"] as string, action, StringComparison.OrdinalIgnoreCase) || string.IsNullOrEmpty(action));
	Func<string, bool> isAreaActive = area =>
		string.Equals(ViewContext.RouteData.Values["Area"] as string, area, StringComparison.OrdinalIgnoreCase);

	var authUser = Context.GetAuthUser();
	string appName = "Lehrgangsverwaltung";
}

<!DOCTYPE html>
<html lang="de" class="h-100">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<partial name="_Favicon" />
	<meta name="description" content="@appName v@(Program.Version)" />

	<title>@ViewBag.Title | @appName</title>

	<partial name="_CSS" />
	@await RenderSectionAsync("Styles", required: false)

	@await RenderSectionAsync("PreScripts", required: false)
</head>
<body class="h-100">
	<div class="main-page">
		<aside class="sidebar">
			<a asp-area="" asp-controller="Trainings" asp-action="Index" asp-route-id="" class="m-2 mb-1 text-decoration-none d-none d-md-inline text-center">
				<img src="~/images/ASB.svg" />
			</a>
			<hr class="d-none d-md-block">

			<ul class="nav nav-pills flex-column mb-auto mt-5 mt-md-0">
				<partial name="_Menu" />
			</ul>

			<hr>

			<div class="footer">
				@if (authUser == null)
				{
					<div class="text-muted text-center">abgemeldet</div>
				}
				else
				{
					<div class="dropup">
						<a href="#" class="text-decoration-none dropdown-toggle text-caps" data-bs-toggle="dropdown" aria-expanded="false">
							@authUser.GetName()
							@if (authUser.ImpersonatingId.HasValue)
							{
								<span class="fa-solid fa-masks-theater mx-1" title="Benutzer wird imitiert"></span>
							}
						</a>
						<ul class="dropdown-menu dropdown-menu-dark text-small">
							@if (!isActive("", "Account", "Mfa"))
							{
								<li>
									<a asp-area="" asp-controller="Account" asp-action="Index" asp-route-id="" class="dropdown-item" condition-class-active="@isActive("", "Account", "Index")">
										<span class="fa-solid fa-fw fa-user"></span> Profil
									</a>
								</li>
								@if (authUser.IsAdmin)
								{
									<li><hr class="dropdown-divider"></li>
									<li>
										<a asp-area="" asp-controller="Settings" asp-action="Index" asp-route-id="" class="dropdown-item" condition-class-active="@isActive("", "Settings", "")">
											<span class="fa-solid fa-fw fa-gears"></span> Einstellungen
										</a>
									</li>
									<li>
										<a asp-area="" asp-controller="Protocols" asp-action="Index" asp-route-id="" class="dropdown-item" condition-class-active="@isActive("", "Protocols", "")">
											<span class="fa-solid fa-fw fa-clock-rotate-left"></span> Protokoll
										</a>
									</li>
								}
								<li><hr class="dropdown-divider"></li>
							}
							<li>
								<a asp-area="" asp-controller="Account" asp-action="Logout" asp-route-id="" class="dropdown-item">
									<span class="fa-solid fa-fw fa-right-from-bracket"></span> Abmelden
								</a>
							</li>
						</ul>
					</div>
				}
			</div>
		</aside>

		<main class="h-100">
			<div class="navbar navbar-main d-md-none">
				<div class="container-fluid">
					<a asp-area="" asp-controller="Trainings" asp-action="Index" asp-route-id="" class="navbar-brand">
						<img src="~/ico/apple-touch-icon.png" /> @appName
					</a>

					<button class="navbar-toggler" type="button">
						<span class="fa-solid fa-bars"></span>
					</button>
				</div>
			</div>

			<div class="d-flex flex-column main-content">
				<div class="mx-4 my-3">
					@RenderBody()
				</div>

				<footer class="mx-4 mt-auto">
					<div class="d-flex justify-content-between footer mt-2">
						<p class="px-1"><!-- Copyright? / Last Updated? --></p>
						<p class="px-1">
							<span class="fa-solid fa-heart-pulse tp-tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="Status" id="websocket-connection-state"></span>
							<span class="ms-2">v@(Program.Version)</span>
						</p>
					</div>
				</footer>
			</div>

		</main>
	</div>

	<partial name="_JS" />
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>