TrainingPlanning/Controllers/EmailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AMWD.ASBHE.TrainingPlanning.Database;
using AMWD.ASBHE.TrainingPlanning.Database.Entities;
using AMWD.ASBHE.TrainingPlanning.Enums;
using AMWD.ASBHE.TrainingPlanning.Extensions;
using AMWD.ASBHE.TrainingPlanning.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace AMWD.ASBHE.TrainingPlanning.Controllers
{
	[Authorize]
	public class EmailsController : Controller
	{
		private readonly IServiceScopeFactory _serviceScopeFactory;

		public EmailsController(IServiceScopeFactory serviceScopeFactory)
		{
			_serviceScopeFactory = serviceScopeFactory;
		}

		public IActionResult Index()
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			ViewData["Title"] = "E-Mail Versand";
			return View();
		}

		public async Task<IActionResult> Get(long id, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			using var scope = _serviceScopeFactory.CreateScope();
			var dbContext = scope.ServiceProvider.GetService<ServerDbContext>();

			if (dbContext == null)
				return Json(Array.Empty<EmailMessage>());

			try
			{
				var timestamp = DateTime.UnixEpoch.AddMilliseconds(id);
				var emails = await dbContext.EmailMessages
					.Where(m => id == 0 || m.SendAfterDate <= timestamp)
					.OrderByDescending(m => m.SendAfterDate)
					.Take(20)
					.ToListAsync(cancellationToken);

				return Json(emails);
			}
			catch (Exception ex)
			{
				return StatusCode(StatusCodes.Status500InternalServerError, ex.GetMessage());
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete(string id, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			try
			{
				using var scope = _serviceScopeFactory.CreateScope();
				var dbContext = scope.ServiceProvider.GetRequiredService<ServerDbContext>();

				var email = await dbContext.EmailMessages
					.Where(em => em.Id == id)
					.FirstOrDefaultAsync(cancellationToken);
				if (email == null)
					return NotFound("E-Mail konnte nicht gefunden werden");

				if (email.Status != EmailMessageStatus.Pending && email.Status != EmailMessageStatus.Error)
					return BadRequest($"Nur E-Mails im Status '{EmailMessageStatus.Pending.GetDisplayName()}' oder '{EmailMessageStatus.Error.GetDisplayName()}' können gelöscht werden");

				using var transaction = await dbContext.BeginTransactionAsync(cancellationToken);

				dbContext.EmailAttachments.RemoveRange(dbContext.EmailAttachments.Where(ea => ea.EmailMessageId == email.Id));
				dbContext.EmailMessages.Remove(email);

				await dbContext.SaveChangesAsync(cancellationToken);
				await transaction.CommitAsync(cancellationToken);

				return Ok();
			}
			catch (Exception ex)
			{
				return StatusCode(StatusCodes.Status500InternalServerError, ex.GetRecursiveMessage());
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteMulti(string[] ids, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			if (ids == null || ids.Length == 0)
				return BadRequest();

			try
			{
				using var scope = _serviceScopeFactory.CreateScope();
				var logger = scope.ServiceProvider.GetRequiredService<ILogger<EmailsController>>();
				var dbContext = scope.ServiceProvider.GetRequiredService<ServerDbContext>();

				var deletedIds = new List<string>();
				foreach (string id in ids)
				{
					var email = await dbContext.EmailMessages
							.Where(em => em.Id == id)
							.FirstOrDefaultAsync(cancellationToken);
					if (email == null)
						continue;

					if (email.Status != EmailMessageStatus.Pending && email.Status != EmailMessageStatus.Error)
						continue;

					try
					{
						using var transaction = await dbContext.BeginTransactionAsync(cancellationToken);

						dbContext.EmailAttachments.RemoveRange(dbContext.EmailAttachments.Where(ea => ea.EmailMessageId == email.Id));
						dbContext.EmailMessages.Remove(email);

						await dbContext.SaveChangesAsync(cancellationToken);
						await transaction.CommitAsync(cancellationToken);
						deletedIds.Add(email.Id);
					}
					catch (Exception ex)
					{
						logger.LogWarning(ex, $"Deleting email ({email.Id}) failed: {ex.GetMessage()}");
					}
				}

				return Json(deletedIds);
			}
			catch (Exception ex)
			{
				return StatusCode(StatusCodes.Status500InternalServerError, ex.GetRecursiveMessage());
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> ReSend(string id, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			try
			{
				using var scope = _serviceScopeFactory.CreateScope();
				var dbContext = scope.ServiceProvider.GetRequiredService<ServerDbContext>();

				var email = await dbContext.EmailMessages
					.Where(em => em.Id == id)
					.FirstOrDefaultAsync(cancellationToken);
				if (email == null)
					return NotFound("E-Mail konnte nicht gefunden werden");

				if (email.Status != EmailMessageStatus.Sent && email.Status != EmailMessageStatus.Error)
					return BadRequest($"Nur E-Mails im Status '{EmailMessageStatus.Sent.GetDisplayName()}' oder '{EmailMessageStatus.Error.GetDisplayName()}' können erneut versendet werden");

				email.Status = EmailMessageStatus.Pending;
				email.UpdatedAt = DateTime.UtcNow;

				await dbContext.SaveChangesAsync(cancellationToken);
				return Json(email);
			}
			catch (Exception ex)
			{
				return StatusCode(StatusCodes.Status500InternalServerError, ex.GetRecursiveMessage());
			}
		}
	}
}

TrainingPlanning/Controllers/ProtocolsController.cs
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AMWD.ASBHE.TrainingPlanning.Database;
using AMWD.ASBHE.TrainingPlanning.Extensions;
using AMWD.ASBHE.TrainingPlanning.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace AMWD.ASBHE.TrainingPlanning.Controllers
{
	[Authorize]
	public class ProtocolsController : Controller
	{
		private readonly IServiceScopeFactory _serviceScopeFactory;

		public ProtocolsController(IServiceScopeFactory serviceScopeFactory)
		{
			_serviceScopeFactory = serviceScopeFactory;
		}

		public IActionResult Index()
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			using var scope = _serviceScopeFactory.CreateScope();
			var logContext = scope.ServiceProvider.GetService<LogDbContext>();

			ViewData["Title"] = "Server-Protokoll";
			ViewData["IsAvailable"] = logContext != null;
			return View();
		}

		public async Task<IActionResult> Get(long id, CancellationToken cancellationToken)
		{
			var authUser = HttpContext.GetAuthUser();
			if (!authUser.IsAdmin)
				return Forbid();

			using var scope = _serviceScopeFactory.CreateScope();
			var logContext = scope.ServiceProvider.GetService<LogDbContext>();

			if (logContext == null)
				return Json(Array.Empty<SerilogEntry>());

			try
			{
				var entries = await logContext.Entries
					.Where(e => e.Id < id || id == 0)
					.OrderByDescending(e => e.Id)
					.Take(50)
					.ToListAsync(cancellationToken);

				return Json(entries);
			}
			catch (Exception ex)
			{
				return StatusCode(StatusCodes.Status500InternalServerError, ex.GetMessage());
			}
		}
	}
}

TrainingPlanning/Views/Protocols/Index.cshtml
<h1 class="h1"><span class="fa-solid fa-clock-rotate-left"></span> Server-Protokoll</h1>

@if ((bool?)ViewBag.IsAvailable == true)
{
	<div class="table-responsive">
		<table class="table" id="log">
			<thead class="table-light">
				<tr>
					<th scope="col">Zeit</th>
					<th scope="col">Level</th>
					<th scope="col">Nachricht</th>
					<th scope="col">&nbsp;</th>
				</tr>
			</thead>
			<tbody class="tp-template">
				<tr>
					<td data-text="timestampISO" data-type="luxon" data-format="dd.MM.yyyy HH:mm:ss"></td>
					<td data-text="level"></td>
					<td data-text="message"></td>
					<td class="text-end">
						<button type="button" class="btn btn-sm btn-outline-dark details" title="Details">
							<span class="fa-solid fa-fw fa-magnifying-glass"></span>
						</button>
					</td>
				</tr>
			</tbody>
			<tbody class="items">
				<!-- filled via JavaScript -->
			</tbody>
			<tfoot>
				<tr>
					<td colspan="4" class="text-center">
						<a href="#" id="load-entries">Ältere Einträge laden</a>
					</td>
				</tr>
			</tfoot>
		</table>
	</div>

	<div class="modal fade" id="detail-modal" tabindex="-1" aria-labelledby="dm-title" aria-hidden="true">
		<div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="dm-title"><span class="fa-solid fa-magnifying-glass"></span> Details</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Schließen"></button>
				</div>
				<div class="modal-body">
					<h4 class="properties h4">Eigenschaften</h4>
					<div class="properties table-responsive">
						<table class="table table-sm">
							<thead class="thead-light">
								<tr>
									<th scope="col">Name</th>
									<th scope="col">Wert</th>
								</tr>
							</thead>
							<tbody id="properties"></tbody>
						</table>
					</div>

					<h4 class="h4 exception">Ausnahme</h4>
					<p class="exception whitespace-pre overflow-auto" id="exception"></p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-dark" data-bs-dismiss="modal">Schließen</button>
				</div>
			</div>
		</div>
	</div>


	@section Scripts {
		<environment include="Development">
			<script type="text/javascript" src="~/js/pages/protocols.js?v=@(Program.StartupTime.ToString("yyyyMMddHHmm"))" asp-integrity="false"></script>
		</environment>
		<environment exclude="Development">
			<script type="text/javascript" src="~/js/pages/protocols.js?v=@(Program.Version)" asp-integrity="true"></script>
		</environment>

		<script type="text/javascript">
			Protocols.Initialize('@Url.Action("Get", "Protocols", new { area = "" })');
		</script>
	}
}
else
{
	<div class="alert alert-info" role="alert">
		<span class="fa-solid fa-fw fa-circle-info"></span> Datenbank basiertes Logging ist derzeit nicht eingerichtet. Es kann in der Konfigurationsdatei eingestellt werden.
	</div>
}

TrainingPlanning/Views/Protocols/_Menu.cshtml
<li class="nav-item">
	<a asp-area="" asp-controller="Trainings" asp-action="Index" asp-route-id="" class="nav-link">
		<span class="fa-solid fa-fw fa-house"></span> Übersicht
	</a>
</li>

<li class="nav-item">
	<a asp-area="" asp-controller="Protocols" asp-action="Index" asp-route-id="" class="nav-link active">
		<span class="fa-solid fa-fw fa-clock-rotate-left"></span> Server-Protokoll
	</a>
</li>
<li class="nav-item">
	<a asp-area="" asp-controller="Emails" asp-action="Index" asp-route-id="" class="nav-link">
		<span class="fa-solid fa-fw fa-envelopes-bulk"></span> E-Mail Versand
	</a>
</li>